name: MRFG

on:
  schedule:
cron: '0 */5 * * *'  # Every 5 hours
  push:
    branches:
main  # Main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
name: Checkout code
        uses: actions/checkout@v2

name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the Node.js 20

name: Install dependencies
        run: npm install

name: start
        run: npm start # Start Bot
